<a href="https://colab.research.google.com/github/Husnain2692/Python_Learning_with_Apna_College/blob/main/Lec11_Numpy_2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

marks = np.array([70, 80, 90, 95])

np.save("marks.npy", marks)

In [ ]:
marks = np.load("marks.npy")
print(marks)

[70 80 90 95]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
np.savetxt("marks.txt", arr)
arr = np.loadtxt("marks.txt")
print(arr)

[1. 2. 3. 4. 5.]


In [ ]:
import numpy as np
data = np.loadtxt("marks.txt")
print(data)


[1. 2. 3. 4. 5.]


In [ ]:
with open("marks.csv","w") as file:
  file.write("10,20,30\n40,50,60")

In [ ]:
import numpy as np
data = np.loadtxt("marks.csv", delimiter=",")
print(data)

[[10. 20. 30.]
 [40. 50. 60.]]


In [ ]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print(arr[1, 2])

60


In [ ]:
import numpy as np

arr = np.array([[[10, 20], [30, 40]],
                [[50, 60], [70, 80]]])

print(arr[1, 0, 1])

60


In [ ]:
import numpy as np

marks = np.array([45, 60, 80, 95, 30])

print(marks[marks > 60])

[80 95]


In [ ]:
import numpy as np

marks = np.array([70, 80, 90])
marks = marks + 5
print(marks)

[75 85 95]


In [ ]:
import numpy as np

arr = np.array([2, 4, 6])
arr = arr * 2
print(arr)

[ 4  8 12]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30])
print(arr.dtype)

int64


In [ ]:
arr = arr.astype(float)
print(arr)
print(arr.dtype)

[10. 20. 30.]
float64


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
print(a + b)
# Output: [5 7 9]

[5 7 9]


In [ ]:
print(a * b)
# Output: [4 10 18]

[ 4 10 18]


In [ ]:
print(a / b)
# Output: [0.25 0.4  0.5]

[0.25 0.4  0.5 ]


In [ ]:
print(a ** 2)
# Output: [1 4 9]

[1 4 9]


In [ ]:
pixels = np.array([100, 120, 140])

# Divide by 255 to normalize pixel values
pixels = pixels / 255
print(pixels)
# Output: [0.39215686 0.47058824 0.54901961]

[0.39215686 0.47058824 0.54901961]


In [ ]:
import numpy as np

arr = np.array([4, 9, 16])
print(np.sqrt(arr))
# Output: [2. 3. 4.]

[2. 3. 4.]


In [ ]:
arr = np.array([1, 2, 3])
print(np.exp(arr))
# Output: [ 2.71828183  7.3890561  20.08553692]

[ 2.71828183  7.3890561  20.08553692]


In [ ]:
angle = np.array([0])
print(np.sin(angle))
# Output: [0.]

[0.]


In [ ]:
marks = np.array([60, 80, 90])

In [ ]:
print(np.max(marks))
# Output: 90

90


In [ ]:
print(np.min(marks))
# Output: 60

60


In [ ]:
print(np.mean(marks))
# Output: 76.66666666666667

76.66666666666667


In [ ]:
print(np.sum(marks))
# Output: 230

230
