<a href="https://colab.research.google.com/github/Husnain2692/Python_Learning_with_Apna_College/blob/main/Lec10_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
numbers = [10,220,30,40]
arr=np.array(numbers)
print(arr)

[ 10 220  30  40]


In [ ]:
import numpy as np
arr =np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
#Formula to find gap [(start - stop)/(Intervals - 1)]
import numpy as np
ar = np.linspace(0, 10, 5)
print(ar)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
import numpy as np
ar = np.random.rand(10)
print(ar)

[0.58165488 0.87447149 0.4461026  0.48081861 0.94063458 0.635411
 0.50432385 0.26810175 0.17061359 0.56147455]


In [ ]:
import numpy as np
ar = np.random.randint(1, 10, 5)
print(ar)

[8 4 4 7 4]


In [ ]:
import numpy as np
ar = np.random.randint(10)
print(ar)

1


In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
new_arr = arr.reshape(3, 3)
print(new_arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
#reshape values in the form of rows
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
new_arr = arr.reshape(2, 4)
print(new_arr)

[[10 20 30 40]
 [50 60 70 80]]


In [ ]:
import numpy as np
ar = np.array([5, 18, 12, 7])
print(arr.min())

10


In [ ]:
import numpy as np
ar = np.array([5, 18, 12, 7])
print(arr.max())

80


In [ ]:
import numpy as np
ar = np.array([5, 18, 12, 7])
print(arr.argmax())

7


In [ ]:
import numpy as np
ar = np.array([5, 18, 12, 7])
print(arr.argmin())

0


In [ ]:
import numpy as np

ar = np.array([[5, 18, 12, 7],
               [6, 7, 9, 11]])

print(ar.shape)

(2, 4)


In [ ]:
import numpy as np
ar = np.array([5, 18, 12, 7])
print(ar.dtype)

int64


In [ ]:
import numpy as np
ar = np.array([5, 18, 12, 7])
print(ar.size)

4


In [ ]:
import numpy as np
ar = np.array([5, 18, 12, 7])
print(ar.ndim)

1


In [ ]:
import numpy as np

ar = np.array([[5, 18, 12, 7],
               [6, 10, 15, 20]])

print(ar.ndim)

2


In [ ]:
import numpy as np
arr = np.array([5, 18, 12, 7])
copy_arr = arr.copy()
print(copy_arr)

[ 5 18 12  7]


In [ ]:
import numpy as np

arr = np.array([5, 18, 12, 7])
view_arr = arr.view()  # Creates a shallow copy (view)
print(view_arr)

[ 5 18 12  7]


In [ ]:
import numpy as np

arr = np.array([1, 2, 4])
new_arr = np.insert(arr, 2, 3)
print(new_arr)

[1 2 3 4]


In [ ]:
import numpy as np

arr = np.array([8, 2, 5, 1])
print(np.sort(arr))

[1 2 5 8]


In [ ]:
import numpy as np

arr = np.array([8, 2, 5, 1])

# Method 1: Sort ascending, then reverse using array slicing [::-1]
reverse_sorted = np.sort(arr)[::-1]
print(reverse_sorted)

[8 5 2 1]


In [ ]:
import numpy as np

arr = np.array([8, 2, 5, 1])

# Delete the element at index 2 (value 5)
new_arr = np.delete(arr, 2)
print(new_arr)

[8 2 1]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Combine two arrays into one
combined_arr = np.concatenate((arr1, arr2))
print(combined_arr)

[1 2 3 4 5 6]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Split array into 3 equal parts
split_arr = np.split(arr, 3)
print(split_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]
